const swaggerAutogen = require("swagger-autogen")();

swaggerAutogen(
    "../swagger/output.json",
    [ "../src/index.ts" ],
    {
        info: {
            title: "Social Network for Music | API",
            description: "A RESTful API that works as the core of SNM (Social Network for Music)."
        },
        host: "davi0k-vps.com",
        schemes: [ "https" ],
        definitions: {
            User: {
                "_id": "65a3105e29c6516ab2dd1b38",
                "email": "gordon.freeman@hotmail.com",
                "username": "gordon.freeman",
                "artists": [
                    "59rqdbDiB9oXuZggah1syh",
                    "1dfeR4HaWDbWqFHLkxsg1d",
                    "711MCceyCBcFnzjGY4Q7Un"
                ],
                "genres": [
                    "rock"
                ]
            },
            Playlist: {
                "_id": "65df6fe0aef53429367c76c9",
                "owner": {
                    "_id": "65a3105e29c6516ab2dd1b38",
                    "username": "davi0k"
                },
                "title": "Midnight tunes vol.2",
                "description": "All the best night tunes to play at 00:00am!",
                "public": true,
                "tags": [
                    "night"
                ],
                "tracks": [{
                    $ref: "#/definitions/Track"
                }],
                "followers": [
                    "65df84edaef53429367c7c77"
                ]
            },
            PlaylistPreview: {
                "_id": "65df6fe0aef53429367c76c9",
                "owner": {
                    "_id": "65a3105e29c6516ab2dd1b38",

                    "username": "gordon.freeman"
                },
                "title": "City 17's Tunes",
                "public": true,
                "tags": [
                    "city",
                    "apocalyptic",
                    "dystopia"
                ],
                "followers": [
                    "65df84edaef53429367c7c77",
                    "65df90c4aef53429367c7d7f"
                ],
                "totalTracks": 3
            },
            Track: {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/67hb7towEyKvt5Z8Bx306c"
                            },
                            "href": "https://api.spotify.com/v1/artists/67hb7towEyKvt5Z8Bx306c",
                            "id": "67hb7towEyKvt5Z8Bx306c",
                            "name": "Empire Of The Sun",
                            "type": "artist",
                            "uri": "spotify:artist:67hb7towEyKvt5Z8Bx306c"
                        }
                    ],
                    "available_markets": [
                        "AR",
                        "AU",
                        "AT",
                        "BE",
                        "BO",
                        "BR",
                        "BG",
                        "CA",
                        "CL",
                        "CO",
                        "CR",
                        "CY",
                        "CZ",
                        "DK",
                        "DO",
                        "DE",
                        "EC",
                        "EE",
                        "SV",
                        "FI",
                        "FR",
                        "GR",
                        "GT",
                        "HN",
                        "HK",
                        "HU",
                        "IS",
                        "IE",
                        "IT",
                        "LV",
                        "LT",
                        "LU",
                        "MY",
                        "MT",
                        "MX",
                        "NL",
                        "NZ",
                        "NI",
                        "NO",
                        "PA",
                        "PY",
                        "PE",
                        "PH",
                        "PL",
                        "PT",
                        "SG",
                        "SK",
                        "ES",
                        "SE",
                        "CH",
                        "TW",
                        "TR",
                        "UY",
                        "US",
                        "GB",
                        "AD",
                        "LI",
                        "MC",
                        "ID",
                        "JP",
                        "TH",
                        "VN",
                        "RO",
                        "IL",
                        "ZA",
                        "SA",
                        "AE",
                        "BH",
                        "QA",
                        "OM",
                        "KW",
                        "EG",
                        "MA",
                        "DZ",
                        "TN",
                        "LB",
                        "JO",
                        "PS",
                        "IN",
                        "BY",
                        "KZ",
                        "MD",
                        "UA",
                        "AL",
                        "BA",
                        "HR",
                        "ME",
                        "MK",
                        "RS",
                        "SI",
                        "KR",
                        "BD",
                        "PK",
                        "LK",
                        "GH",
                        "KE",
                        "NG",
                        "TZ",
                        "UG",
                        "AG",
                        "AM",
                        "BS",
                        "BB",
                        "BZ",
                        "BT",
                        "BW",
                        "BF",
                        "CV",
                        "CW",
                        "DM",
                        "FJ",
                        "GM",
                        "GE",
                        "GD",
                        "GW",
                        "GY",
                        "HT",
                        "JM",
                        "KI",
                        "LS",
                        "LR",
                        "MW",
                        "MV",
                        "ML",
                        "MH",
                        "FM",
                        "NA",
                        "NR",
                        "NE",
                        "PW",
                        "PG",
                        "WS",
                        "SM",
                        "ST",
                        "SN",
                        "SC",
                        "SL",
                        "SB",
                        "KN",
                        "LC",
                        "VC",
                        "SR",
                        "TL",
                        "TO",
                        "TT",
                        "TV",
                        "VU",
                        "AZ",
                        "BN",
                        "BI",
                        "KH",
                        "CM",
                        "TD",
                        "KM",
                        "GQ",
                        "SZ",
                        "GA",
                        "GN",
                        "KG",
                        "LA",
                        "MO",
                        "MR",
                        "MN",
                        "NP",
                        "RW",
                        "TG",
                        "UZ",
                        "ZW",
                        "BJ",
                        "MG",
                        "MU",
                        "MZ",
                        "AO",
                        "CI",
                        "DJ",
                        "ZM",
                        "CD",
                        "CG",
                        "IQ",
                        "LY",
                        "TJ",
                        "VE",
                        "ET",
                        "XK"
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/5B6XfyHHYawyLkEvNvhSPh"
                    },
                    "href": "https://api.spotify.com/v1/albums/5B6XfyHHYawyLkEvNvhSPh",
                    "id": "5B6XfyHHYawyLkEvNvhSPh",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ab67616d0000b273f3aa0e6ca22a382007f61e4d",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/ab67616d00001e02f3aa0e6ca22a382007f61e4d",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/ab67616d00004851f3aa0e6ca22a382007f61e4d",
                            "width": 64
                        }
                    ],
                    "name": "Walking On A Dream (10th Anniversary Edition)",
                    "release_date": "2008-10-03",
                    "release_date_precision": "day",
                    "total_tracks": 16,
                    "type": "album",
                    "uri": "spotify:album:5B6XfyHHYawyLkEvNvhSPh"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/67hb7towEyKvt5Z8Bx306c"
                        },
                        "href": "https://api.spotify.com/v1/artists/67hb7towEyKvt5Z8Bx306c",
                        "id": "67hb7towEyKvt5Z8Bx306c",
                        "name": "Empire Of The Sun",
                        "type": "artist",
                        "uri": "spotify:artist:67hb7towEyKvt5Z8Bx306c"
                    }
                ],
                "available_markets": [
                    "AR",
                    "AU",
                    "AT",
                    "BE",
                    "BO",
                    "BR",
                    "BG",
                    "CA",
                    "CL",
                    "CO",
                    "CR",
                    "CY",
                    "CZ",
                    "DK",
                    "DO",
                    "DE",
                    "EC",
                    "EE",
                    "SV",
                    "FI",
                    "FR",
                    "GR",
                    "GT",
                    "HN",
                    "HK",
                    "HU",
                    "IS",
                    "IE",
                    "IT",
                    "LV",
                    "LT",
                    "LU",
                    "MY",
                    "MT",
                    "MX",
                    "NL",
                    "NZ",
                    "NI",
                    "NO",
                    "PA",
                    "PY",
                    "PE",
                    "PH",
                    "PL",
                    "PT",
                    "SG",
                    "SK",
                    "ES",
                    "SE",
                    "CH",
                    "TW",
                    "TR",
                    "UY",
                    "US",
                    "GB",
                    "AD",
                    "LI",
                    "MC",
                    "ID",
                    "JP",
                    "TH",
                    "VN",
                    "RO",
                    "IL",
                    "ZA",
                    "SA",
                    "AE",
                    "BH",
                    "QA",
                    "OM",
                    "KW",
                    "EG",
                    "MA",
                    "DZ",
                    "TN",
                    "LB",
                    "JO",
                    "PS",
                    "IN",
                    "BY",
                    "KZ",
                    "MD",
                    "UA",
                    "AL",
                    "BA",
                    "HR",
                    "ME",
                    "MK",
                    "RS",
                    "SI",
                    "KR",
                    "BD",
                    "PK",
                    "LK",
                    "GH",
                    "KE",
                    "NG",
                    "TZ",
                    "UG",
                    "AG",
                    "AM",
                    "BS",
                    "BB",
                    "BZ",
                    "BT",
                    "BW",
                    "BF",
                    "CV",
                    "CW",
                    "DM",
                    "FJ",
                    "GM",
                    "GE",
                    "GD",
                    "GW",
                    "GY",
                    "HT",
                    "JM",
                    "KI",
                    "LS",
                    "LR",
                    "MW",
                    "MV",
                    "ML",
                    "MH",
                    "FM",
                    "NA",
                    "NR",
                    "NE",
                    "PW",
                    "PG",
                    "WS",
                    "SM",
                    "ST",
                    "SN",
                    "SC",
                    "SL",
                    "SB",
                    "KN",
                    "LC",
                    "VC",
                    "SR",
                    "TL",
                    "TO",
                    "TT",
                    "TV",
                    "VU",
                    "AZ",
                    "BN",
                    "BI",
                    "KH",
                    "CM",
                    "TD",
                    "KM",
                    "GQ",
                    "SZ",
                    "GA",
                    "GN",
                    "KG",
                    "LA",
                    "MO",
                    "MR",
                    "MN",
                    "NP",
                    "RW",
                    "TG",
                    "UZ",
                    "ZW",
                    "BJ",
                    "MG",
                    "MU",
                    "MZ",
                    "AO",
                    "CI",
                    "DJ",
                    "ZM",
                    "CD",
                    "CG",
                    "IQ",
                    "LY",
                    "TJ",
                    "VE",
                    "ET",
                    "XK"
                ],
                "disc_number": 1,
                "duration_ms": 198440,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUEI10800039"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/5r5cp9IpziiIsR6b93vcnQ"
                },
                "href": "https://api.spotify.com/v1/tracks/5r5cp9IpziiIsR6b93vcnQ",
                "id": "5r5cp9IpziiIsR6b93vcnQ",
                "is_local": false,
                "name": "Walking On A Dream",
                "popularity": 82,
                "preview_url": null,
                "track_number": 2,
                "type": "track",
                "uri": "spotify:track:5r5cp9IpziiIsR6b93vcnQ"
            },
            Artist: {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/67hb7towEyKvt5Z8Bx306c"
                },
                "followers": {
                    "href": null,
                    "total": 1410412
                },
                "genres": [
                    "australian dance",
                    "australian electropop",
                    "dance rock",
                    "indietronica",
                    "neo-synthpop"
                ],
                "href": "https://api.spotify.com/v1/artists/67hb7towEyKvt5Z8Bx306c",
                "id": "67hb7towEyKvt5Z8Bx306c",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab6761610000e5ebe51c443e9e8c1952c80357b4",
                        "width": 640
                    },
                    {
                        "height": 320,
                        "url": "https://i.scdn.co/image/ab67616100005174e51c443e9e8c1952c80357b4",
                        "width": 320
                    },
                    {
                        "height": 160,
                        "url": "https://i.scdn.co/image/ab6761610000f178e51c443e9e8c1952c80357b4",
                        "width": 160
                    }
                ],
                "name": "Empire Of The Sun",
                "popularity": 75,
                "type": "artist",
                "uri": "spotify:artist:67hb7towEyKvt5Z8Bx306c"
            }
        },
        securityDefinitions: {
            JWT: {
                type: "apiKey",
                in: "header",
                name: "authorization",

                description: "Enter the JWT with the 'Bearer ' prefix (e.g. 'Bearer [token]')."
            }
        }
    }
);
